### ISSUE TITLE
LGTM Emoji

### ISSUE THREAD

**Issue by simonbukin** [maybe-finance/emojis#1]
Figured we could use an LGTM react in the Discord server, so I whipped one up real quick. Would be good to get a font ID on the "gm" that's in the original set of emojis, since I just approximated one that was close enough.

Here's a preview

![Screenshot 2024-01-19 at 3 24 44 PM](https://github.com/maybe-finance/emojis/assets/8992420/a94e50e4-76c2-4328-b265-6b57d0e7dea4)

Here's the [Figma file](https://www.figma.com/file/O3TYQYNptOtuCk2dcCbCbx/Maybe-Emojis-(Community)?type=design&node-id=1%3A11&mode=design&t=eOgljyF785gu1pBn-1)

**Comment by Shpigford** [comment]
Font is Monument Extended Heavy! Would need to use that to keep consistency.

**Comment by simonbukin** [comment]
Fixed! Now using Monument Extended.

![Screenshot 2024-01-29 at 11 57 22 AM](https://github.com/maybe-finance/emojis/assets/8992420/965b909a-f836-45a5-8b8b-cead00291104)

**Comment by Shpigford** [comment]
Perfect! Shipped!
